# Generated by Django 4.2.18 on 2025-01-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gourmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('rating', models.IntegerField(default=1)),
            ],
        ),
    ]
